# Generated by Django 4.2.3 on 2023-07-19 16:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('role', models.CharField(choices=[('artist', 'Artist'), ('buyer', 'Buyer')], max_length=255)),
                ('avatar', models.ImageField(upload_to=accounts.models.upload_avatar)),
                ('bio', models.TextField(max_length=2000)),
                ('walletAddress', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'MyUser',
                'verbose_name_plural': 'MyUsers',
                'ordering': ['-created_at'],
            },
        ),
    ]
