# Generated by Django 4.2.3 on 2023-07-20 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_first_name_myuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_reverse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
