# Generated by Django 4.2.3 on 2023-07-28 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nfts', '0003_alter_nft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='artist',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
