# Generated by Django 4.2.3 on 2023-07-28 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nfts', '0004_alter_nft_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'buyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
