# Generated by Django 3.2 on 2023-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0005_alter_nft_highest_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
